import { NextResponse } from 'next/server'

const INDEXNOW_KEY = 'a599bf3dbd75444488d556a0d7f4be3c'
const HOST = 'www.nassohcar.com'
const KEY_LOCATION = `https://${HOST}/${INDEXNOW_KEY}.txt`

const URLS = [
  // Main / FR
  'https://www.nassohcar.com',
  'https://www.nassohcar.com/about',
  'https://www.nassohcar.com/location-voiture-tanger-pas-cher',
  'https://www.nassohcar.com/location-voiture-tanger-aeroport',
  'https://www.nassohcar.com/location-voiture-tanger',
  'https://www.nassohcar.com/location-voiture-tetouan',
  'https://www.nassohcar.com/contact',
  'https://www.nassohcar.com/faq',
  'https://www.nassohcar.com/fleet',
  'https://www.nassohcar.com/location-voiture-europe',
  'https://www.nassohcar.com/location-voiture-tanger-port',
  'https://www.nassohcar.com/privacy',
  'https://www.nassohcar.com/terms',
  // EN
  'https://www.nassohcar.com/en',
  'https://www.nassohcar.com/en/about',
  'https://www.nassohcar.com/en/car-rental-europe',
  'https://www.nassohcar.com/en/car-rental-tangier',
  'https://www.nassohcar.com/en/car-rental-tangier-airport',
  'https://www.nassohcar.com/en/car-rental-tangier-city-center',
  'https://www.nassohcar.com/en/car-rental-tangier-port',
  'https://www.nassohcar.com/en/car-rental-tangier-port-med',
  'https://www.nassohcar.com/en/car-rental-tetouan',
  'https://www.nassohcar.com/en/cheap-car-rental-tangier',
  'https://www.nassohcar.com/en/contact',
  'https://www.nassohcar.com/en/faq',
  'https://www.nassohcar.com/en/fleet',
  'https://www.nassohcar.com/en/privacy',
  'https://www.nassohcar.com/en/terms',
  // ES
  'https://www.nassohcar.com/es',
  'https://www.nassohcar.com/es/alquiler-coches-aeropuerto',
  'https://www.nassohcar.com/es/alquiler-coches-aeropuerto-tanger',
  'https://www.nassohcar.com/es/alquiler-coches-baratos-tanger',
  'https://www.nassohcar.com/es/alquiler-coches-europa',
  'https://www.nassohcar.com/es/alquiler-coches-tanger',
  'https://www.nassohcar.com/es/alquiler-coches-tanger-centro',
  'https://www.nassohcar.com/es/alquiler-coches-tetuan',
  'https://www.nassohcar.com/es/contacto',
  'https://www.nassohcar.com/es/faq',
  'https://www.nassohcar.com/es/flota',
  'https://www.nassohcar.com/es/sobre-nosotros',
  'https://www.nassohcar.com/es/terminos',
  // Blog FR
  'https://www.nassohcar.com/blog',
  'https://www.nassohcar.com/blog/agence-de-location-de-voitures',
  'https://www.nassohcar.com/blog/agence-location-voiture-aeroport-tanger',
  'https://www.nassohcar.com/blog/agence-location-voiture-tanger',
  'https://www.nassohcar.com/blog/conseils-location-voiture-tanger',
  'https://www.nassohcar.com/blog/guide-tanger-attractions',
  'https://www.nassohcar.com/blog/location-auto-a-long-terme',
  'https://www.nassohcar.com/blog/location-auto-tanger',
  'https://www.nassohcar.com/blog/location-de-voitures-tanger',
  'https://www.nassohcar.com/blog/location-voiture-a-tanger',
  'https://www.nassohcar.com/blog/location-voiture-aeroport-tanger',
  'https://www.nassohcar.com/blog/location-voiture-au-port-de-tanger',
  'https://www.nassohcar.com/blog/location-voiture-au-port-de-tanger-med',
  'https://www.nassohcar.com/blog/location-voiture-longue-duree',
  'https://www.nassohcar.com/blog/location-voiture-maroc',
  'https://www.nassohcar.com/blog/location-voiture-pas-cher',
  'https://www.nassohcar.com/blog/location-voiture-pas-cher-tanger',
  'https://www.nassohcar.com/blog/location-voiture-tanger',
  'https://www.nassohcar.com/blog/location-voiture-tanger-aeroport',
  'https://www.nassohcar.com/blog/location-voiture-tanger-aeroport-pas-cher',
  'https://www.nassohcar.com/blog/location-voiture-tanger-boukhalef',
  'https://www.nassohcar.com/blog/location-voiture-tanger-les-mieux-notes',
  'https://www.nassohcar.com/blog/location-voiture-tanger-maroc',
  'https://www.nassohcar.com/blog/location-voiture-tanger-med',
  'https://www.nassohcar.com/blog/location-voiture-tanger-pas-cher',
  'https://www.nassohcar.com/blog/location-voiture-tanger-port-med',
  'https://www.nassohcar.com/blog/location-voiture-tetouan',
  'https://www.nassohcar.com/blog/location-voiture-tetouan-aeroport',
  'https://www.nassohcar.com/blog/louer-voiture-a-petit-prix-tanger',
  'https://www.nassohcar.com/blog/louer-voiture-aeroport-tanger',
  'https://www.nassohcar.com/blog/trouver-une-voiture-de-location-a-tetouan',
  'https://www.nassohcar.com/blog/voiture-a-louer-au-maroc',
  'https://www.nassohcar.com/blog/voiture-a-louer-tanger',
  'https://www.nassohcar.com/blog/voiture-de-location-a-tetouan',
  // Blog EN
  'https://www.nassohcar.com/en/blog',
  'https://www.nassohcar.com/en/blog/best-rated-car-rentals-tangier',
  'https://www.nassohcar.com/en/blog/car-for-rent-morocco',
  'https://www.nassohcar.com/en/blog/car-for-rent-tangier',
  'https://www.nassohcar.com/en/blog/car-hire-tangier',
  'https://www.nassohcar.com/en/blog/car-rental-agency',
  'https://www.nassohcar.com/en/blog/car-rental-agency-tangier',
  'https://www.nassohcar.com/en/blog/car-rental-agency-tangier-airport',
  'https://www.nassohcar.com/en/blog/car-rental-in-tangier',
  'https://www.nassohcar.com/en/blog/car-rental-morocco',
  'https://www.nassohcar.com/en/blog/car-rental-tangier',
  'https://www.nassohcar.com/en/blog/car-rental-tangier-airport',
  'https://www.nassohcar.com/en/blog/car-rental-tangier-auto',
  'https://www.nassohcar.com/en/blog/car-rental-tangier-boukhalef',
  'https://www.nassohcar.com/en/blog/car-rental-tangier-med',
  'https://www.nassohcar.com/en/blog/car-rental-tangier-med-port',
  'https://www.nassohcar.com/en/blog/car-rental-tangier-morocco',
  'https://www.nassohcar.com/en/blog/car-rental-tangier-port',
  'https://www.nassohcar.com/en/blog/car-rental-tangier-port-med',
  'https://www.nassohcar.com/en/blog/car-rental-tetouan',
  'https://www.nassohcar.com/en/blog/car-rental-tetouan-airport',
  'https://www.nassohcar.com/en/blog/car-rental-tips-tangier',
  'https://www.nassohcar.com/en/blog/cheap-car-rental',
  'https://www.nassohcar.com/en/blog/cheap-car-rental-tangier',
  'https://www.nassohcar.com/en/blog/cheap-car-rental-tangier-airport',
  'https://www.nassohcar.com/en/blog/find-car-rental-in-tetouan',
  'https://www.nassohcar.com/en/blog/guide-tangier-attractions',
  'https://www.nassohcar.com/en/blog/long-term-car-hire',
  'https://www.nassohcar.com/en/blog/long-term-car-rental',
  'https://www.nassohcar.com/en/blog/rent-car-tangier-airport',
  'https://www.nassohcar.com/en/blog/rent-cheap-car-tangier',
  // Blog ES
  'https://www.nassohcar.com/es/blog',
  'https://www.nassohcar.com/es/blog/agencia-alquiler-coches',
  'https://www.nassohcar.com/es/blog/agencia-alquiler-coches-aeropuerto-tanger',
  'https://www.nassohcar.com/es/blog/agencia-alquiler-coches-tanger',
  'https://www.nassohcar.com/es/blog/alquiler-auto-tanger',
  'https://www.nassohcar.com/es/blog/alquiler-coche-en-tanger',
  'https://www.nassohcar.com/es/blog/alquiler-coches-aeropuerto-tanger',
  'https://www.nassohcar.com/es/blog/alquiler-coches-aeropuerto-tetuan',
  'https://www.nassohcar.com/es/blog/alquiler-coches-baratos',
  'https://www.nassohcar.com/es/blog/alquiler-coches-baratos-aeropuerto-tanger',
  'https://www.nassohcar.com/es/blog/alquiler-coches-baratos-tanger',
  'https://www.nassohcar.com/es/blog/alquiler-coches-larga-duracion',
  'https://www.nassohcar.com/es/blog/alquiler-coches-larga-temporada',
  'https://www.nassohcar.com/es/blog/alquiler-coches-marruecos',
  'https://www.nassohcar.com/es/blog/alquiler-coches-puerto-tanger',
  'https://www.nassohcar.com/es/blog/alquiler-coches-puerto-tanger-med',
  'https://www.nassohcar.com/es/blog/alquiler-coches-tanger',
  'https://www.nassohcar.com/es/blog/alquiler-coches-tanger-aeropuerto',
  'https://www.nassohcar.com/es/blog/alquiler-coches-tanger-auto',
  'https://www.nassohcar.com/es/blog/alquiler-coches-tanger-baratos',
  'https://www.nassohcar.com/es/blog/alquiler-coches-tanger-boukhalef',
  'https://www.nassohcar.com/es/blog/alquiler-coches-tanger-marruecos',
  'https://www.nassohcar.com/es/blog/alquiler-coches-tanger-med',
  'https://www.nassohcar.com/es/blog/alquiler-coches-tanger-med-puerto',
  'https://www.nassohcar.com/es/blog/alquiler-coches-tetuan',
  'https://www.nassohcar.com/es/blog/alquiler-de-coches-en-tanger',
  'https://www.nassohcar.com/es/blog/coche-de-alquiler-en-tetuan',
  'https://www.nassohcar.com/es/blog/coche-para-alquilar-marruecos',
  'https://www.nassohcar.com/es/blog/coche-para-alquilar-tanger',
  'https://www.nassohcar.com/es/blog/consejos-alquiler-coches-tanger',
  'https://www.nassohcar.com/es/blog/encontrar-alquiler-coches-tetuan',
  'https://www.nassohcar.com/es/blog/guia-atracciones-tanger',
  'https://www.nassohcar.com/es/blog/mejores-alquileres-coches-tanger',
  'https://www.nassohcar.com/es/blog/rentar-coche-aeropuerto-tanger',
  'https://www.nassohcar.com/es/blog/rentar-coche-barato-tanger',
]

export async function POST() {
  try {
    const res = await fetch('https://www.bing.com/indexnow', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      body: JSON.stringify({
        host: HOST,
        key: INDEXNOW_KEY,
        keyLocation: KEY_LOCATION,
        urlList: URLS,
      }),
    })

    if (res.ok) {
      return NextResponse.json({ success: true, submitted: URLS.length, status: res.status })
    }

    const text = await res.text()
    return NextResponse.json({ success: false, status: res.status, response: text }, { status: res.status })
  } catch (err) {
    return NextResponse.json({ success: false, error: String(err) }, { status: 500 })
  }
}
