import { Metadata } from 'next'
import { Shield, Phone, Mail, MapPin, FileText, Scale, Clock, Users, CheckCircle, AlertTriangle, Info, Globe } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Términos y Condiciones | Nassoh Car - Contrato de Alquiler',
  description: "Lea los términos y condiciones de Nassoh Car para los servicios de alquiler de coches en Marruecos. Entienda sus derechos, responsabilidades y nuestras políticas de alquiler.",
  keywords: 'terminos condiciones nassoh car, contrato alquiler coches, condiciones alquiler marruecos, politicas alquiler coches, terminos legales, contrato alquiler',
  alternates: { canonical: 'https://www.nassohcar.com/es/terminos' },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-gray-50 to-amber-50/30">
      <div className="relative bg-gradient-to-br from-slate-900 via-gray-900 to-slate-800 py-32 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-black/60 via-black/40 to-black/60"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="flex items-center justify-center mb-8"><div className="bg-gradient-to-br from-amber-400/20 to-yellow-500/20 p-8 rounded-3xl backdrop-blur-sm border border-amber-400/30 shadow-2xl"><Scale className="h-10 w-10 text-amber-400 mx-auto" /></div></div>
          <h1 className="text-6xl md:text-7xl font-bold text-white mb-8 tracking-tight">Términos y <span className="bg-gradient-to-r from-amber-400 via-yellow-300 to-amber-400 bg-clip-text text-transparent">Condiciones</span></h1>
          <div className="mt-12 flex justify-center"><div className="bg-gradient-to-r from-amber-500/10 to-yellow-500/10 backdrop-blur-sm border border-amber-400/20 rounded-2xl px-8 py-4"><p className="text-amber-300 font-medium">Fecha de Vigencia: Enero 2024</p></div></div>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 mb-12 border border-gray-200/50">
          <div className="flex items-center mb-8"><div className="bg-gradient-to-br from-amber-500 to-yellow-600 p-4 rounded-2xl mr-6 shadow-lg"><FileText className="h-8 w-8 text-white" /></div><h2 className="text-4xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Información de la Empresa</h2></div>
          <div className="space-y-6 text-gray-700">
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-white/70 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50"><p className="font-semibold text-gray-900 mb-2">Nombre Registrado:</p><p className="text-amber-700 font-medium">Nassoh Car S.A.R.L</p></div>
              <div className="bg-white/70 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50"><p className="font-semibold text-gray-900 mb-2">Registro Comercial (RC):</p><p className="text-amber-700 font-medium">42923</p></div>
            </div>
            <div className="bg-white/70 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50"><p className="font-semibold text-gray-900 mb-2">Número ICE:</p><p className="text-amber-700 font-medium">000018320000060</p></div>
            <div className="bg-gradient-to-r from-amber-50 to-yellow-50 p-8 rounded-2xl border border-amber-200/50"><div className="flex items-center mb-4"><MapPin className="h-6 w-6 text-amber-600 mr-3" /><p className="font-semibold text-gray-900 text-lg">Oficina Registrada y Dirección Operativa:</p></div><p className="text-gray-700 leading-relaxed text-lg">127, Av. Hafid Ibn Abdelbar, Kissariat Al‑Andalous, Inzarane, 1er étage N° 36, Tánger 90100, Marruecos</p></div>
            <div className="flex flex-col sm:flex-row gap-6 mt-8"><div className="flex items-center bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50"><Phone className="h-6 w-6 text-amber-500 mr-3" /><span className="font-medium">+212 531 068 352 / +212 631-630013</span></div><div className="flex items-center bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50"><Mail className="h-6 w-6 text-amber-500 mr-3" /><span className="font-medium">contact@nassohcar.com</span></div></div>
          </div>
        </div>

        <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 mb-12 border border-gray-200/50">
          <h3 className="text-3xl font-bold text-gray-900 mb-6 flex items-center"><div className="bg-gradient-to-br from-amber-500 to-yellow-600 p-3 rounded-xl mr-4 shadow-lg"><Users className="h-7 w-7 text-white" /></div>Alcance de los Servicios</h3>
          <div className="bg-gradient-to-r from-amber-50 to-yellow-50 p-6 rounded-2xl border border-amber-200/50"><p className="text-gray-700 leading-relaxed text-lg">Proporcionamos servicios de alquiler de coches sin conductor (Location de voitures sans chauffeur) para alquiler a corto y largo plazo tanto a particulares como a clientes corporativos en Tánger y sus alrededores.</p></div>
        </div>

        <div className="space-y-10">
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-blue-500 to-blue-600 p-3 rounded-xl mr-4 shadow-lg"><CheckCircle className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Reservas</h3></div><div className="space-y-4">{['Las reservas pueden realizarse por teléfono, WhatsApp, correo electrónico o a través de nuestro sitio web.','Las confirmaciones de reserva están sujetas a la disponibilidad del vehículo.','Se puede requerir un depósito o prepago total dependiendo de la tarifa o duración del alquiler.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-blue-300 transition-all duration-300"><div className="bg-blue-100 p-2 rounded-lg mr-4 mt-1"><CheckCircle className="h-4 w-4 text-blue-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-green-500 to-green-600 p-3 rounded-xl mr-4 shadow-lg"><Clock className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Periodo de Alquiler, Tarifas y Pago</h3></div><div className="space-y-4">{['Las tarifas de alquiler se calculan por día o mes, dependiendo del acuerdo.','Los alquileres a largo plazo pueden beneficiarse de tarifas con descuento.','Todos los precios se cotizan en Dirhams Marroquíes (DHS) a menos que se especifique lo contrario.','Pagos aceptados: efectivo en DHS, transferencia bancaria o métodos electrónicos acordados.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-green-300 transition-all duration-300"><div className="bg-green-100 p-2 rounded-lg mr-4 mt-1"><CheckCircle className="h-4 w-4 text-green-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-purple-500 to-purple-600 p-3 rounded-xl mr-4 shadow-lg"><Shield className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Condición y Uso del Vehículo</h3></div><div className="space-y-4">{['Los vehículos se entregan en condiciones de circulación, limpios, con combustible y con todos los documentos obligatorios.','El arrendatario debe devolver el vehículo en condiciones similares, nivel de combustible y sin daños más allá del desgaste normal.','El uso fuera de Marruecos, el subarriendo o el uso ilegal están estrictamente prohibidos.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-purple-300 transition-all duration-300"><div className="bg-purple-100 p-2 rounded-lg mr-4 mt-1"><CheckCircle className="h-4 w-4 text-purple-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-indigo-500 to-indigo-600 p-3 rounded-xl mr-4 shadow-lg"><Users className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Obligaciones y Requisitos del Conductor</h3></div><div className="space-y-4">{['El arrendatario debe poseer una licencia de conducir válida reconocida en Marruecos y tener una edad mínima, generalmente 21 años.','Cualquier multa, sanción, peaje o infracción de tráfico incurrida es responsabilidad del conductor/arrendatario.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-indigo-300 transition-all duration-300"><div className="bg-indigo-100 p-2 rounded-lg mr-4 mt-1"><CheckCircle className="h-4 w-4 text-indigo-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-red-500 to-red-600 p-3 rounded-xl mr-4 shadow-lg"><Shield className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Seguro y Responsabilidad</h3></div><div className="space-y-4">{['Todos los vehículos están cubiertos por un seguro básico a terceros según lo exigido por la ley marroquí.','El arrendatario es responsable de los costos asociados con daños al vehículo, robo o pérdida total, sujeto a las disposiciones estándar de franquicia.','Pueden estar disponibles exenciones parciales o CDW (Exención de Daños por Colisión) con un costo adicional.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-red-300 transition-all duration-300"><div className="bg-red-100 p-2 rounded-lg mr-4 mt-1"><Shield className="h-4 w-4 text-red-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-orange-500 to-orange-600 p-3 rounded-xl mr-4 shadow-lg"><AlertTriangle className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Cancelación y Modificaciones</h3></div><div className="space-y-4">{['Las cancelaciones deben realizarse al menos 48 horas antes de la fecha de inicio del alquiler para evitar penalizaciones.','Las cancelaciones de última hora o la no presentación pueden incurrir en una tarifa equivalente al primer día de alquiler.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-orange-300 transition-all duration-300"><div className="bg-orange-100 p-2 rounded-lg mr-4 mt-1"><AlertTriangle className="h-4 w-4 text-orange-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-red-50/30 rounded-3xl shadow-2xl p-10 border border-red-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-red-600 to-red-700 p-3 rounded-xl mr-4 shadow-lg"><AlertTriangle className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-red-800 to-red-600 bg-clip-text text-transparent">Terminación</h3></div><div className="space-y-4">{['Nos reservamos el derecho de terminar o suspender el contrato de alquiler inmediatamente en caso de: uso no autorizado, mal uso, falta de pago o violación de los T&C.','El arrendatario debe devolver el vehículo inmediatamente y puede perder cualquier depósito.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-red-200/50 hover:border-red-300 transition-all duration-300"><div className="bg-red-100 p-2 rounded-lg mr-4 mt-1"><AlertTriangle className="h-4 w-4 text-red-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-blue-50/30 rounded-3xl shadow-2xl p-10 border border-blue-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-blue-600 to-blue-700 p-3 rounded-xl mr-4 shadow-lg"><Shield className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-blue-800 to-blue-600 bg-clip-text text-transparent">Privacidad y Protección de Datos</h3></div><div className="space-y-4">{['Recopilamos datos personales necesarios para la reserva y el cumplimiento legal.','La información personal se procesa de acuerdo con las leyes de privacidad marroquíes y se utiliza únicamente para la administración del alquiler.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-blue-200/50 hover:border-blue-300 transition-all duration-300"><div className="bg-blue-100 p-2 rounded-lg mr-4 mt-1"><Shield className="h-4 w-4 text-blue-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-purple-50/30 rounded-3xl shadow-2xl p-10 border border-purple-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-purple-600 to-purple-700 p-3 rounded-xl mr-4 shadow-lg"><Scale className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-purple-800 to-purple-600 bg-clip-text text-transparent">Ley Aplicable y Disputas</h3></div><div className="space-y-4">{['Estos Términos y Condiciones se rigen por las leyes del Reino de Marruecos.','Cualquier disputa que surja se someterá a los tribunales de Tánger.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-purple-200/50 hover:border-purple-300 transition-all duration-300"><div className="bg-purple-100 p-2 rounded-lg mr-4 mt-1"><Scale className="h-4 w-4 text-purple-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-amber-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-amber-600 to-yellow-600 p-3 rounded-xl mr-4 shadow-lg"><Info className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-amber-800 to-amber-600 bg-clip-text text-transparent">Modificaciones</h3></div><div className="bg-gradient-to-r from-amber-50 to-yellow-50 p-6 rounded-2xl border border-amber-200/50"><p className="text-gray-700 leading-relaxed text-lg">Nos reservamos el derecho de modificar estos Términos y Condiciones en cualquier momento. Los cambios entran en vigor tras su publicación en nuestro sitio web o comunicación al cliente.</p></div></div>
        </div>

        <div className="bg-gradient-to-br from-amber-500 via-yellow-500 to-amber-600 rounded-3xl p-12 mt-16 shadow-2xl border border-amber-300/50 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-black/10 to-transparent"></div>
          <div className="relative">
            <h3 className="text-4xl font-bold text-white mb-8 text-center">¿Necesita Asistencia Legal?</h3>
            <p className="text-amber-100 text-center mb-8 text-lg max-w-2xl mx-auto">Nuestro equipo de soporte está disponible para ayudar a aclarar cualquier término o responder a sus preguntas</p>
            <div className="flex flex-col sm:flex-row justify-center items-center gap-8"><div className="group flex items-center bg-white/20 backdrop-blur-sm p-6 rounded-2xl border border-white/30"><div className="bg-white/20 p-3 rounded-xl mr-4"><Phone className="h-7 w-7 text-white" /></div><span className="text-xl font-semibold text-white">+212 631-630013</span></div><div className="group flex items-center bg-white/20 backdrop-blur-sm p-6 rounded-2xl border border-white/30"><div className="bg-white/20 p-3 rounded-xl mr-4"><Mail className="h-7 w-7 text-white" /></div><span className="text-xl font-semibold text-white">contact@nassohcar.com</span></div></div>
          </div>
        </div>
      </div>
    </div>
  )
}
