import { Metadata } from 'next'
import { Shield, Phone, Mail, MapPin, FileText, Scale, Clock, Users, CheckCircle, AlertTriangle, Info, Globe } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Terms & Conditions | Nassoh Car - Rental Agreement',
  description: "Read Nassoh Car's terms and conditions for car rental services in Morocco. Understand your rights, responsibilities, and our rental policies.",
  keywords: 'terms conditions nassoh car, car rental agreement, rental terms morocco, car rental policies, legal terms, rental contract',
  alternates: { canonical: 'https://www.nassohcar.com/en/terms' },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-gray-50 to-amber-50/30">
      <div className="relative bg-gradient-to-br from-slate-900 via-gray-900 to-slate-800 py-32 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-black/60 via-black/40 to-black/60"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="flex items-center justify-center mb-8"><div className="bg-gradient-to-br from-amber-400/20 to-yellow-500/20 p-8 rounded-3xl backdrop-blur-sm border border-amber-400/30 shadow-2xl"><Scale className="h-10 w-10 text-amber-400 mx-auto" /></div></div>
          <h1 className="text-6xl md:text-7xl font-bold text-white mb-8 tracking-tight">Terms & <span className="bg-gradient-to-r from-amber-400 via-yellow-300 to-amber-400 bg-clip-text text-transparent">Conditions</span></h1>
          <div className="mt-12 flex justify-center"><div className="bg-gradient-to-r from-amber-500/10 to-yellow-500/10 backdrop-blur-sm border border-amber-400/20 rounded-2xl px-8 py-4"><p className="text-amber-300 font-medium">Effective Date: January 2024</p></div></div>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 mb-12 border border-gray-200/50">
          <div className="flex items-center mb-8"><div className="bg-gradient-to-br from-amber-500 to-yellow-600 p-4 rounded-2xl mr-6 shadow-lg"><FileText className="h-8 w-8 text-white" /></div><h2 className="text-4xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Company Information</h2></div>
          <div className="space-y-6 text-gray-700">
            <div className="grid md:grid-cols-2 gap-6">
              <div className="bg-white/70 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50"><p className="font-semibold text-gray-900 mb-2">Registered Name:</p><p className="text-amber-700 font-medium">Nassoh Car S.A.R.L</p></div>
              <div className="bg-white/70 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50"><p className="font-semibold text-gray-900 mb-2">Commercial Register (RC):</p><p className="text-amber-700 font-medium">42923</p></div>
            </div>
            <div className="bg-white/70 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50"><p className="font-semibold text-gray-900 mb-2">ICE Number:</p><p className="text-amber-700 font-medium">000018320000060</p></div>
            <div className="bg-gradient-to-r from-amber-50 to-yellow-50 p-8 rounded-2xl border border-amber-200/50"><div className="flex items-center mb-4"><MapPin className="h-6 w-6 text-amber-600 mr-3" /><p className="font-semibold text-gray-900 text-lg">Registered Office & Operating Address:</p></div><p className="text-gray-700 leading-relaxed text-lg">127, Av. Hafid Ibn Abdelbar, Kissariat Al‑Andalous, Inzarane, 1er étage N° 36, Tangier 90100, Morocco</p></div>
            <div className="flex flex-col sm:flex-row gap-6 mt-8"><div className="flex items-center bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50"><Phone className="h-6 w-6 text-amber-500 mr-3" /><span className="font-medium">+212 531 068 352 / +212 631-630013</span></div><div className="flex items-center bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50"><Mail className="h-6 w-6 text-amber-500 mr-3" /><span className="font-medium">contact@nassohcar.com</span></div></div>
          </div>
        </div>

        <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 mb-12 border border-gray-200/50">
          <h3 className="text-3xl font-bold text-gray-900 mb-6 flex items-center"><div className="bg-gradient-to-br from-amber-500 to-yellow-600 p-3 rounded-xl mr-4 shadow-lg"><Users className="h-7 w-7 text-white" /></div>Scope of Services</h3>
          <div className="bg-gradient-to-r from-amber-50 to-yellow-50 p-6 rounded-2xl border border-amber-200/50"><p className="text-gray-700 leading-relaxed text-lg">We provide car rental services without driver (Location de voitures sans chauffeur) for short‑term and long‑term rental to both individuals and corporate clients in Tangier and surrounding areas.</p></div>
        </div>

        <div className="space-y-10">
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-blue-500 to-blue-600 p-3 rounded-xl mr-4 shadow-lg"><CheckCircle className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Reservations & Booking</h3></div><div className="space-y-4">{['Reservations may be made by phone, WhatsApp, email, or through our website.','Booking confirmations are subject to vehicle availability.','A deposit or full prepayment may be required depending on tariff or rental duration.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-blue-300 transition-all duration-300"><div className="bg-blue-100 p-2 rounded-lg mr-4 mt-1"><CheckCircle className="h-4 w-4 text-blue-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-green-500 to-green-600 p-3 rounded-xl mr-4 shadow-lg"><Clock className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Rental Period, Rates & Payment</h3></div><div className="space-y-4">{['Rental fees are calculated by day or month, depending on the agreement.','Long‑term rentals may benefit from discounted rates.','All prices are quoted in Moroccan Dirhams (DHS) unless otherwise specified.','Payments accepted: cash in DHS, bank transfer, or agreed electronic methods.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-green-300 transition-all duration-300"><div className="bg-green-100 p-2 rounded-lg mr-4 mt-1"><CheckCircle className="h-4 w-4 text-green-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-purple-500 to-purple-600 p-3 rounded-xl mr-4 shadow-lg"><Shield className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Vehicle Condition & Usage</h3></div><div className="space-y-4">{['Vehicles are delivered in roadworthy condition, clean, fueled, and with all mandatory documents.','Lessee must return the vehicle in similar condition, fuel level, and with no damage beyond normal wear and tear.','Use outside Morocco, sub‑rental, or illegal use is strictly prohibited.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-purple-300 transition-all duration-300"><div className="bg-purple-100 p-2 rounded-lg mr-4 mt-1"><CheckCircle className="h-4 w-4 text-purple-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-indigo-500 to-indigo-600 p-3 rounded-xl mr-4 shadow-lg"><Users className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Driver's Obligations & Requirements</h3></div><div className="space-y-4">{['Lessee must hold a valid driving licence recognized in Morocco and be over a minimum age, typically 21 years.','Any fines, penalties, tolls, or traffic violations incurred are the responsibility of the driver/lessee.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-indigo-300 transition-all duration-300"><div className="bg-indigo-100 p-2 rounded-lg mr-4 mt-1"><CheckCircle className="h-4 w-4 text-indigo-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-red-500 to-red-600 p-3 rounded-xl mr-4 shadow-lg"><Shield className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Insurance & Liability</h3></div><div className="space-y-4">{['All vehicles are covered by basic third‑party insurance as mandated by Moroccan law.','Lessee is liable for costs associated with damage to the vehicle, theft, or total loss, subject to standard deductible provisions.','Partial waivers or CDW (Collision Damage Waiver) may be available at extra cost.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-red-300 transition-all duration-300"><div className="bg-red-100 p-2 rounded-lg mr-4 mt-1"><Shield className="h-4 w-4 text-red-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-gray-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-orange-500 to-orange-600 p-3 rounded-xl mr-4 shadow-lg"><AlertTriangle className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-700 bg-clip-text text-transparent">Cancellation & Amendments</h3></div><div className="space-y-4">{['Cancellations must be made at least 48 hours before the rental start date to avoid penalty.','Last‑minute cancellations or no‑shows may incur a fee equivalent to the first rental day.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50 hover:border-orange-300 transition-all duration-300"><div className="bg-orange-100 p-2 rounded-lg mr-4 mt-1"><AlertTriangle className="h-4 w-4 text-orange-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-red-50/30 rounded-3xl shadow-2xl p-10 border border-red-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-red-600 to-red-700 p-3 rounded-xl mr-4 shadow-lg"><AlertTriangle className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-red-800 to-red-600 bg-clip-text text-transparent">Termination</h3></div><div className="space-y-4">{['We reserve the right to terminate or suspend the rental agreement immediately in case of: unauthorized use, misuse, non‑payment, or violation of T&C.','Lessee must return the vehicle immediately and may forfeit any deposit.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-red-200/50 hover:border-red-300 transition-all duration-300"><div className="bg-red-100 p-2 rounded-lg mr-4 mt-1"><AlertTriangle className="h-4 w-4 text-red-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-blue-50/30 rounded-3xl shadow-2xl p-10 border border-blue-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-blue-600 to-blue-700 p-3 rounded-xl mr-4 shadow-lg"><Shield className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-blue-800 to-blue-600 bg-clip-text text-transparent">Privacy & Data Protection</h3></div><div className="space-y-4">{['We collect personal data required for booking and legal compliance.','Personal information is processed in accordance with Moroccan privacy laws and is used solely for rental administration.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-blue-200/50 hover:border-blue-300 transition-all duration-300"><div className="bg-blue-100 p-2 rounded-lg mr-4 mt-1"><Shield className="h-4 w-4 text-blue-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-purple-50/30 rounded-3xl shadow-2xl p-10 border border-purple-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-purple-600 to-purple-700 p-3 rounded-xl mr-4 shadow-lg"><Scale className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-purple-800 to-purple-600 bg-clip-text text-transparent">Governing Law & Disputes</h3></div><div className="space-y-4">{['These Terms & Conditions are governed by the laws of the Kingdom of Morocco.','Any disputes arising shall be submitted to the courts of Tangier.'].map((item, index) => (<div key={index} className="flex items-start bg-white/70 backdrop-blur-sm p-4 rounded-xl border border-purple-200/50 hover:border-purple-300 transition-all duration-300"><div className="bg-purple-100 p-2 rounded-lg mr-4 mt-1"><Scale className="h-4 w-4 text-purple-600" /></div><p className="text-gray-700 leading-relaxed">{item}</p></div>))}</div></div>
          <div className="group bg-gradient-to-br from-white via-gray-50/50 to-amber-50/30 rounded-3xl shadow-2xl p-10 border border-amber-200/50"><div className="flex items-center mb-6"><div className="bg-gradient-to-br from-amber-600 to-yellow-600 p-3 rounded-xl mr-4 shadow-lg"><Info className="h-7 w-7 text-white" /></div><h3 className="text-3xl font-bold bg-gradient-to-r from-amber-800 to-amber-600 bg-clip-text text-transparent">Modifications</h3></div><div className="bg-gradient-to-r from-amber-50 to-yellow-50 p-6 rounded-2xl border border-amber-200/50"><p className="text-gray-700 leading-relaxed text-lg">We reserve the right to amend these Terms & Conditions at any time. Changes take effect upon publication on our website or communication to the client.</p></div></div>
        </div>

        <div className="bg-gradient-to-br from-amber-500 via-yellow-500 to-amber-600 rounded-3xl p-12 mt-16 shadow-2xl border border-amber-300/50 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-black/10 to-transparent"></div>
          <div className="relative">
            <h3 className="text-4xl font-bold text-white mb-8 text-center">Need Legal Assistance?</h3>
            <p className="text-amber-100 text-center mb-8 text-lg max-w-2xl mx-auto">Our support team is available to help clarify any terms or answer your questions</p>
            <div className="flex flex-col sm:flex-row justify-center items-center gap-8"><div className="group flex items-center bg-white/20 backdrop-blur-sm p-6 rounded-2xl border border-white/30"><div className="bg-white/20 p-3 rounded-xl mr-4"><Phone className="h-7 w-7 text-white" /></div><span className="text-xl font-semibold text-white">+212 631-630013</span></div><div className="group flex items-center bg-white/20 backdrop-blur-sm p-6 rounded-2xl border border-white/30"><div className="bg-white/20 p-3 rounded-xl mr-4"><Mail className="h-7 w-7 text-white" /></div><span className="text-xl font-semibold text-white">contact@nassohcar.com</span></div></div>
          </div>
        </div>
      </div>
    </div>
  )
}
